### PR TITLE
John conroy/fix donor metadata anchor

### LINKED ISSUE #1158: Missing metadata anchor (at least for donors)
For example: https://portal.stage.hubmapconsortium.org/browse/donor/3439871e0617807d2711465a249af9a5

The other links under `Sections` work, but not `Metadata`.

### PR DESCRIPTION
**Pull request by john-conroy**
Fix #1158. Is it worth refactoring some of the repeated code in the entity detail pages?

### CODE REVIEW

File: context/app/static/js/components/Detail/utils.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export function getSectionOrder(possibleSections, optionalSectionsToInclude) {
+  return possibleSections.filter(
+    (section) => !(section in optionalSectionsToInclude) || optionalSectionsToInclude[section] === true,
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/utils.js:3]:
```suggestion
    (section) => !(section in optionalSectionsToInclude) || optionalSectionsToInclude[section],
```

File: context/app/static/js/components/Detail/DetailLayout/utils.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import { capitalizeString } from 'js/helpers/functions';
+
+function getSectionFromString(s) {
+  return [s, { text: capitalizeString(s), hash: s }];
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/DetailLayout/utils.js:4]: I don't think this is a change in this PR, but if it's not complicated, could the lists we give to `getSectionOrder` have the intended capitalization? In the past I've been boxed in when I started like this, and then there was some name that needed non-standard capitalization.

If it's an easy change in this PR, great, or file an issue if you think it's worthwhile.

**Review by mccalluc — APPROVED** [review]
