### PR TITLE
Mccalluc/prop type my lists

### LINKED ISSUE #2806: Resources Menu: Failed prop type
I click on the "Resources" menu and get this error in the console:

```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `DropdownLink`, expected `string`.
    in DropdownLink (created by ResourceLinks)
```

### LINKED ISSUE #2807: Prop type error on my-lists
```
Warning: Failed prop type: Invalid prop `buttons` supplied to `SectionButtonRow`.
    in SectionButtonRow (created by SectionButtonRow__SpacedSectionButtonRow)
```

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #2807
- Fix #2806

### CODE REVIEW

File: context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ function SavedEntitiesTable({ savedEntities, deleteCallback, setShouldDisplaySav
           </BottomAlignedTypography>
         }
         buttons={
-          selectedRowsSize > 0 && (
+          selectedRowsSize === 0 ? null : (
```
Comment (john-conroy) [inline context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx:67]: What does this fix?

**Review by john-conroy — APPROVED** [review]

File: context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx (hunk 1 above)
Comment (mccalluc) [reply context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx:67]: Returning `false` is a prop-type error, but `null` is fine. Maybe there's a better idiom?
