### PR TITLE
John conroy/fix prov table duplication

### LINKED ISSUE #667: Duplicate entity tiles for the current entity in the provenance table are being created on each additional render

### PR DESCRIPTION
**Pull request by john-conroy**
Fixes #667

### CODE REVIEW

File: context/app/static/js/components/Detail/ProvTable/ProvTable.jsx [hunk 1]
```diff
@@ -9,9 +9,9 @@ import ProvTableDerivedLink from '../ProvTableDerivedLink';
 function ProvTable(props) {
   const { uuid, entity_type, typesToSplit, ancestors, assayMetadata } = props;
 
-  ancestors.push(assayMetadata);
+  const entities = [...ancestors, assayMetadata];
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/ProvTable/ProvTable.jsx:12]:
```suggestion
  // Make a new list rather modifying old one in place: Caused duplication in UI.
  const entities = [...ancestors, assayMetadata];
```
