### PR TITLE
John conroy/update globus link

### LINKED ISSUE #802: Implement redesign of Globus file browser
Design: #506

### LINKED ISSUE #840: Determined unanticipated status code message for globus link
We should have a message prepared in the event we receive a response with an unanticipated status code.

Temporarily I'm using `Unexpected <Status>. Report error to help@hubmapconsortium.org`.

### PR DESCRIPTION
**Pull request by john-conroy**
Fixes #802 . Fixes #840 .

Screen Shot 2020-07-17 at 1 40 51 PM

Screen Shot 2020-07-17 at 1 41 36 PM

Screen Shot 2020-07-17 at 1 42 43 PM

Screen Shot 2020-07-17 at 1 48 02 PM

Screen Shot 2020-07-17 at 1 48 23 PM

### CODE REVIEW

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+import { LightBlueLink } from 'shared-styles/Links';
+import { StyledExternalLinkIcon } from './style';
+
+const messages = {
+  200: 'Files are available through the Globus Research Data Management System. Access dataset',
+  401: 'Unauthorized access to the Globus Research Management System (bad or expired token). If you believe this to be an error, please contact',
+  403: 'Access to files on the Globus Research Management system are restricted. You may not have access to these files because the Consortium is still curating data and/or the data is protected data that requires you to be a member of the Consortium “Protected Data Group”. Such protected data will be available via dbGaP in the future. If you believe this to be an error, please contact',
+  404: 'Files are not available through the Globus Research Management system. If you believe this to be an error, please contact',
+  500: 'Unexpected server or other error. Report error to',
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:13]: Having these fragments of messages that get completed different ways depending on context may be confusing. Possible alternative:
```
if (statusCode === 200) {
   return (
       <>
           {`Files are available through the Globus Research Data Management System. Access dataset ${display_doi} on `}
           <LightBlueLink underline="none" variant="body2" href={url}>
            Globus <StyledExternalLinkIcon />
          </LightBlueLink>
      </>
   )
```
and then handle the errors.

I guess the larger theme is a worry about putting two much logic inside the JSX.

File: context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx [hunk 2]
```diff
@@ -16,28 +24,45 @@ function GlobusLink(props) {
...
+      <DetailSectionPaper>
+        <Flex>
+          <StyledTypography variant="h6">Bulk Data Transfer</StyledTypography>
+          {statusCode === 200 ? <StyledSuccessIcon /> : <StyledInfoIcon />}
+        </Flex>
+        <Typography variant="body2">
+          {statusCodesWithMessages.has(statusCode) ? (
+            <GlobusLinkMessage statusCode={statusCode} url={url} display_doi={display_doi} />
+          ) : (
+            <GlobusLinkMessage statusCode={500} url={url} />
```
[the remark this answers is not in the document]
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx:54]: I'll file an issue for Nils/Tiffany to determine a fallback message.

File: context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx [hunk 3]
```diff
@@ -1,12 +1,20 @@
...
+import GlobusLinkMessage from '../GlobusLinkMessage';
+
+const statusCodesWithMessages = new Set([200, 401, 403, 404, 500]);
 
 function GlobusLink(props) {
-  const { uuid, entityEndpoint, fileBrowserDisplayed } = props;
-  const [globusUrlText, setGlobusUrlText] = React.useState({ url: null, text: 'Please wait...' });
+  const { uuid, entityEndpoint, display_doi } = props;
+  const [loading, setLoading] = React.useState(true);
+  const [globusUrlText, setGlobusUrlText] = React.useState({ url: null, statusCode: null });
```
[the remark this answers is not in the document]
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx:16]: I'll rename the variable.

File: context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx [hunk 4]
```diff
@@ -1,12 +1,20 @@
...
+import { StyledTypography, CenteredDiv, MarginTopDiv, Flex, StyledInfoIcon, StyledSuccessIcon } from './style';
+import GlobusLinkMessage from '../GlobusLinkMessage';
+
+const statusCodesWithMessages = new Set([200, 401, 403, 404, 500]);
 
 function GlobusLink(props) {
-  const { uuid, entityEndpoint, fileBrowserDisplayed } = props;
-  const [globusUrlText, setGlobusUrlText] = React.useState({ url: null, text: 'Please wait...' });
+  const { uuid, entityEndpoint, display_doi } = props;
+  const [loading, setLoading] = React.useState(true);
```
[the remark this answers is not in the document]
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx:15]: Can you further explain your concern for using multiple useState hooks? The react docs state it's a normal practice.

File: context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx]: Filed #840

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 1 above)
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:12]: I used guard clauses instead of the ternary. Let me know if this is your preference.

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+};
+
+function GlobusLinkMessage(props) {
+  const { statusCode, url, display_doi } = props;
+
+  if (statusCode === 200) {
+    return (
+      <Typography variant="body2">
+        {`Files are available through the Globus Research Data Management System. Access dataset' ${display_doi} on `}
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:21]:
```suggestion
        {`Files are available through the Globus Research Data Management System. Access dataset ${display_doi} on `}
```

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+        <LightBlueLink underline="none" variant="body2" href={url}>
+          Globus <StyledExternalLinkIcon />
+        </LightBlueLink>
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:24]:
```suggestion
        </LightBlueLink>
        .
```

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+          help@hubmapconsortium.org
+        </LightBlueLink>
+        .
+      </Typography>
+    );
+  }
+
+  return (
+    <Typography variant="body2">
+      {`Unexpected error. Report error to `}
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:43]:
```suggestion
      {`Unexpected error ${statusCode}. Report error to `}
```
Slightly more information in the bug report.

Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:43]: Originally I had something similar #840

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 6 above)
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:24]: The period was not included in the design. @tsliaw do we want a period after the icon?

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 7 above)
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:43]: @tsliaw would this be acceptable?

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 6 above)
Comment (tsliaw) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:24]: Yes, just make sure the period is not a part of the link and is #000000

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 7 above)
Comment (tsliaw) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:43]: This works

File: context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx (hunk 6 above)
Comment (john-conroy) [reply context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx:24]: Yes it wouldn't be a part of the link and is the default typography color
