### PR TITLE
John conroy/remove dev server from ci

### LINKED ISSUE #1387: 1000s of chokidar errors on Github CI?
Like this, though the details vary:
```
Error from chokidar (/home/runner/work/portal-ui/portal-ui/context/node_modules/@material-ui/icons):
Error: ENOSPC: System limit for number of file watchers reached, watch 
'/home/runner/work/portal-ui/portal-ui/context/node_modules/@material-ui/icons/package.json'
```

I haven't run the test suite locally in a long while, and maybe this was the case on Travis, and isn't related to Github CI?

### PR DESCRIPTION
**Pull request by john-conroy**
Fix #1387. Do we need to everything between lines 34-46 of `test.sh` or can we just run ./copy-app-conf.sh?

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -43,12 +43,7 @@ if [ ! -z "$TRAVIS" ] || [ ! -z "$GH_ACTIONS" ]; then
     cat context/instance/app.conf
   )
 fi
-set -m; ./dev-start.sh & set +m  # Without job control, I had trouble killing parent and children.
-PID=$!
-server_up 5001  # Not really needed: Cypress will wait for response.
-end-to-end/test.sh
-kill -TERM -$PID  # Kill dev server processes
-end dev-start
+end copy-app-conf
```
Comment (john-conroy) [inline test.sh:46]: Do we need to keep all of this or can we just run `./copy-app-conf.sh`

**Comment by john-conroy** [comment]
Passing on travis, but failing on Github Actions. Going to set this to draft.

**Comment by john-conroy** [comment]
Fixed and ready for review.

File: copy-app-conf.sh [hunk 2]
```diff
@@ -0,0 +1,12 @@
+#!/usr/bin/env bash
+CONTEXT=context
+
+APP_INSTANCE="$CONTEXT/instance"
```
Comment (mccalluc) [inline copy-app-conf.sh:4]:
```suggestion
APP_INSTANCE="context/instance"
```
In the original `$CONTEXT` is reused; Here it isn't.

File: test.sh [hunk 3]
```diff
@@ -43,15 +43,11 @@ if [ ! -z "$TRAVIS" ] || [ ! -z "$GH_ACTIONS" ]; then
     cat context/instance/app.conf
   )
 fi
-set -m; ./dev-start.sh & set +m  # Without job control, I had trouble killing parent and children.
-PID=$!
-server_up 5001  # Not really needed: Cypress will wait for response.
-end-to-end/test.sh
```
Comment (mccalluc) [inline test.sh:49]: Doesn't `end-to-end/test.sh` still need to be called somewhere?

File: test.sh [hunk 4]
```diff
@@ -43,15 +43,11 @@ if [ ! -z "$TRAVIS" ] || [ ! -z "$GH_ACTIONS" ]; then
...
-kill -TERM -$PID  # Kill dev server processes
-end dev-start
+end copy-app-conf
 
 
 start flake8
+pip install -r context/requirements.txt > /dev/null
 # Unit tests require dev dependencies beyond requirements.txt.
 pip install -r context/requirements-dev.txt > /dev/null
```
Comment (mccalluc) [inline test.sh:52]: If we're getting rid of the weird `dev-start.sh` on CI, installs should probably just move outside this script.

**Review by mccalluc — CHANGES_REQUESTED** [review]
Don't we still need to call `end-to-end/test.sh`? Sorry if I'm missing something. Other comments minor.

File: test.sh (hunk 3 above)
Comment (john-conroy) [reply test.sh:49]: Isn't it being called on line 75?

File: test.sh (hunk 4 above)
Comment (john-conroy) [reply test.sh:52]: I can move the installs to the yml files for Github Actions and Travis. It would also then require you to run the installs before running this script locally. Should I wait until we decide between the two options?

Comment (john-conroy) [reply test.sh]: From stand-up: we'll move the installs out of test.sh. Those running `test.sh` locally can be entrusted to make installs.

File: test.sh (hunk 3 above)
Comment (mccalluc) [reply test.sh:49]: Yep! Sorry to be confused.

**Review by mccalluc — APPROVED** [review]
