### PR TITLE
John conroy/fix analysis details link ext bug

### LINKED ISSUE #1215: Handle dag provenance origin fields which do not have .git extension in provenance analysis details
From slack:

> future versions will not include the '.git' extension but some data already present in the PROD database does include the '.git'.  In any case, both URLs are valid, so I think it's best to accept both forms.

### PR DESCRIPTION
**Pull request by john-conroy**
Towards #1215. As noted in the issue, I will wait to close it until the slack thread is concluded. Does this work or would you prefer a regex solution?

Update: Fix #1215.

### CODE REVIEW

**Comment by john-conroy** [comment]
Fix #1215.

File: context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.jsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { CwlIcon, FlexLightBlueLink, PrimaryTextDivider, StyledListItem } from '
 function ProvAnalysisDetailsLink(props) {
   const { data } = props;
 
-  const trimmedOrigin = data.origin.split('.').slice(0, -1).join('.');
+  const trimmedOrigin = data.origin.endsWith('.git') ? data.origin.split('.').slice(0, -1).join('.') : data.origin;
```
Comment (mccalluc) [inline context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.jsx:9]:
```suggestion
  const trimmedOrigin = data.origin.replace(/\.git$/, '');
```
I think this would be more clear.

**Review by mccalluc — CHANGES_REQUESTED** [review]
Prefer regex, but everything else looks good. Thanks!
