### PR TITLE
John conroy/prettier should fail ci

### LINKED ISSUE #1565: prettier errors should be ci errors
from  #1563:
> Also fixes a prettier error from a code review suggestion from an earlier PR. These keep popping up, should we make prettier fail our ci to catch these earlier?

Yes, I think that would be good: I'd like the pre-commit checks to be a subset of UI, and if I'm understanding correctly, that's not currently the case? Thanks for noting this, @john-conroy .

### PR DESCRIPTION
**Pull request by john-conroy**
Fix #1565. Add linting, which includes prettier, to test script. I think we previously got this from dev-start when it was in the test script, but lost it when it was removed.

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -57,9 +57,12 @@ start pytest
 pytest context/app
 end pytest
 
+start lint
+cd context
+npm run lint
+end lint
```
Comment (mccalluc) [inline test.sh:63]:
```suggestion
cd -
end lint
```

**Review by mccalluc — COMMENTED** [review]
Small preference to have the same state at the end of the block as at the start... Here, it's obvious enough, but if these get bigger, it's easier to miss.

... or, alternatively, pull the `cd` outside of the `start`/`end` block... So you have all the tests that run at one directory level, and then the `cd` to another directory stands out.

Or whatever you think best.

File: test.sh (hunk 1 above)
Comment (john-conroy) [reply test.sh:64]: Moved the cds outside of the start/end blocks.

**Review by mccalluc — APPROVED** [review]
