### PR TITLE
softer warning from entities API

### LINKED ISSUE #2088: Explaing Entities 403 in log
If the user doesn't have privs, there's an expected 403... but then we have an extra `console.error`:
```
console.error('Entities API failed', response);
```

If it's a 403, we shouldn't error: Instead, it'd be better to log a message that explains the 403 that preceded it is not unexpected.

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #2088

### CODE REVIEW

File: context/app/static/js/components/files/GlobusLink/GlobusLink.jsx [hunk 1]
```diff
@@ -24,7 +24,12 @@ function GlobusLink(props) {
           headers: requestHeaders,
         });
         if (!response.ok) {
-          console.error('Entities API failed', response);
+          if (response.status === 403) {
```
Comment (john-conroy) [inline context/app/static/js/components/files/GlobusLink/GlobusLink.jsx:27]: Should we check for existence of a nexus token?

**Review by john-conroy — APPROVED** [review]

File: context/app/static/js/components/files/GlobusLink/GlobusLink.jsx (hunk 1 above)
Comment (mccalluc) [reply context/app/static/js/components/files/GlobusLink/GlobusLink.jsx:27]: I don't know that that would change anything: You could be logged in, but still not have sufficient privs, and a 403 would still be an expected response. 

If I'm misunderstanding, let me know?
